try cpp-linter-action

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -3,13 +3,16 @@ on:
   push:
   pull_request:
 jobs:
-  clang-format:
-    runs-on: ubuntu-22.04
+  cpp-linter:
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: lint cpp files
-        run: |
-          sudo apt-get install -y clang-format
-          git clang-format --style=file main || exit 1
-          echo "clang-format lint successful"
+      - uses: actions/checkout@v3
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        with:
+          style: file
+      - name: Linter Failed
+        if: steps.linter.outputs.checks-failed > 0
+        run: echo "Linting Failed"
+        run: exit 1
 
